### ISSUE TITLE
Initalize the builder for mainnet

### ISSUE THREAD

**Issue by leongb** [Zondax/ledger-zcash-rs#15]
Currently the builder is initialized for test-net.
https://github.com/Zondax/ledger-zcash-rs/blob/de3c54f2f4a82991aad176ea278b937bcaabfad1/zcash-hsmbuilder/src/lib.rs#L250

:link: [zboto Link](https://app.clickup.com/t/2karha2)

**Comment by jleni** [comment]
Depends on integration
