### ISSUE TITLE
Put the zkproof and anchor check back in

### ISSUE THREAD

**Issue by leongb** [Zondax/ledger-zcash-rs#5]
https://github.com/Zondax/ledger-zcash-rs/blob/69cc7504a7a6a1e4083f374987c8e2a40f196925/zcash-hsmbuilder/src/txbuilder_ledger.rs#L519-L531

https://github.com/Zondax/ledger-zcash-rs/blob/69cc7504a7a6a1e4083f374987c8e2a40f196925/zcash-hsmbuilder/src/prover_ledger.rs#L154-L184

:link: [zboto Link](https://app.clickup.com/t/2karha4)

**Comment by jleni** [comment]
What's the status here?

**Comment by leongb** [comment]
Currently for CI tests we created fake transaction data to work with. We can re-enable these checks and close the issue when we have ''real'' transaction data to use in the CI tests. Note that these checks are only ''additional sanity checks'' on blockchain data.

**Comment by leongb** [comment]
The todo's would be to:
- Go through the process of generating proper zcash blocks and how rseed is stored in these blocks
- Generate multiple good blocks (as we use more than one spend note in CI tests), having the same root/anchor
- Integrate those blocks (with witnesses) in the CI tests.
